repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: [ '--maxkb=1000' ]
      - id: check-case-conflict
        exclude: '{{ cookiecutter.repo_name }}'
      - id: check-merge-conflict
        exclude: '{{ cookiecutter.repo_name }}'
      - id: check-symlinks
        exclude: '{{ cookiecutter.repo_name }}'
      - id: check-yaml
        exclude: '{{ cookiecutter.repo_name }}'
      - id: debug-statements
        exclude: '{{ cookiecutter.repo_name }}'
      - id: end-of-file-fixer
        exclude: '{{ cookiecutter.repo_name }}'
      - id: requirements-txt-fixer
        exclude: '{{ cookiecutter.repo_name }}'
      - id: trailing-whitespace
        exclude: '{{ cookiecutter.repo_name }}'

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.1
    hooks:
      - id: pyupgrade
        args: ["--py38-plus"]
        name: Upgrade code
        exclude: '{{ cookiecutter.repo_name }}'

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        additional_dependencies: [tomli]
        #args: ["--write-changes"] # uncomment if you want to get automatic fixing
        exclude: '{{ cookiecutter.repo_name }}'

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        additional_dependencies: [tomli]
        args: ["--in-place"]
        exclude: '{{ cookiecutter.repo_name }}'

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.2
    hooks:
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ "--fix", "--preview" ]
        exclude: '{{ cookiecutter.repo_name }}'
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
        args: [ "--preview" ]
        exclude: '{{ cookiecutter.repo_name }}'

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-admon
          - mdformat-footnote
          - mdformat_frontmatter
          - mdformat-mkdocs
          - mdformat-toc
        # Ignore readme as well, for flexibility
        exclude: '^({{ cookiecutter.repo_name }}/|README.md$)'
        args: [ "--number" ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.9.0"
    hooks:
      - id: mypy
        # Use pyproject.toml if possible instead of adding command line parameters here
        args: []
        additional_dependencies:
          # Type stubs
          - pytest
          # Use individual packages since types-all has been deprecated
          - types-DateTimeRange
          - types-Deprecated
          - types-Flask
          - types-JACK-Client
          - types-Jinja2
          - types-Markdown
          - types-MarkupSafe
          - types-Pillow
          - types-PyJWT
          - types-PyMySQL
          - types-PyYAML
          - types-Routes
          - types-Werkzeug
          - types-aiofiles
          - types-annoy
          - types-atomicwrites
          - types-backports
          - types-backports-abc
          - types-bleach
          - types-boto
          - types-cachetools
          - types-certifi
          - types-characteristic
          - types-chardet
          - types-click
          - types-click-spinner
          - types-colorama
          - types-contextvars
          - types-croniter
          - types-cryptography
          - types-dataclasses
          - types-dateparser
          - types-decorator
          - types-docopt
          - types-docutils
          - types-emoji
          - types-enum34
          - types-fb303
          - types-filelock
          - types-first
          - types-freezegun
          - types-frozendict
          - types-futures
          - types-geoip2
          - types-ipaddress
          - types-itsdangerous
          - types-kazoo
          - types-maxminddb
          - types-mock
          - types-mypy-extensions
          - types-nmap
          - types-openssl-python
          - types-orjson
          - types-paramiko
          - types-pathlib2
          - types-polib
          - types-protobuf
          - types-pyRFC3339
          - types-pyaudio
          - types-pycurl
          - types-pyfarmhash
          - types-pymssql
          - types-pysftp
          - types-python-dateutil
          - types-python-gflags
          - types-python-slugify
          - types-pytz
          - types-pyvmomi
          - types-redis
          - types-requests
          - types-retry
          - types-scribe
          - types-setuptools
          - types-simplejson
          - types-singledispatch
          - types-six
          - types-tabulate
          - types-termcolor
          - types-toml
          - types-tornado
          - types-typed-ast
          - types-tzlocal
          - types-ujson
          - types-waitress
          - types-xxhash
          - types-tqdm
        exclude: '{{ cookiecutter.repo_name }}'

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest -v tests
        language: system
        pass_filenames: false
        always_run: true
