site_name: ML Project - Cookiecutter
site_description: A project template and directory structure for Python data science projects.
site_dir: docs-site
repo_url: https://github.com/xultaeculcis/ml-project-cookiecutter
edit_uri: edit/main/docs/docs
copyright: Copyright 2023 xultaeculcis
theme:
  name: material
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - md_in_html
  - meta
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.tabbed
nav:
  - Home: index.md
  - Getting started: guide.md
  - Contributing: contributing.md
  - License: license.md
plugins:
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
  - search
watch:
  - docs/
