steps:
  - script: |
      pre-commit install
    displayName: "Install pre-commit hooks"

  - script: |
      SKIP=pytest-check uvx pre-commit run --all-files
    displayName: "Run simplified pre-commit hooks"
