steps:
  - script: |
      uvx pytest -vv --junitxml=junit/unit-test.xml --cov=src --cov-report=xml
    displayName: Run PyTest
    env:
      ENVIRONMENT: $<< parameters.env >>

  - task: PublishCodeCoverageResults@2
    inputs:
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
      failIfCoverageEmpty: True
