trigger: none

pr:
  - main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: env
    type: string
    default: dev
    values:
      - dev
      - staging
      - prod

variables:
  - name: lock_file_location
    value: conda-lock-dev.yml
  - name: conda_env_name
    value: ci-env

stages:
  - stage: pre_commit
    displayName: Run pre-commit hooks
    jobs:
      - template: ./jobs/code-qa.yaml

  - stage: tests
    displayName: Run tests
    jobs:
      - template: ./jobs/test-suite.yaml
        parameters:
          env: $<< parameters.env >>
          lock_file_location: $<< variables.lock_file_location >>
          conda_env_name: $<< variables.conda_env_name >>
