trigger: none

pr:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: "pre_commit_hooks"
    displayName: "Run pre-commit hooks"
    jobs:
      - job: "pre_commit_hooks"
        displayName: "Run pre-commit hooks"
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "3.11"
              addToPath: true

          - script: |
              python -m pip install --upgrade pip
              pip install pre-commit pytest cookiecutter
              pre-commit install
            displayName: "Install dependencies"

          - script: |
              pre-commit run --all-files
            displayName: "Run pre-commit hooks"
