name: docs

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/docs.yaml
      - docs/**
      - mkdocs.yml
      - README.md
  workflow_dispatch:  # Allow manual triggering from any branch

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.x

      - run: pip install mkdocs-material mkdocs-gen-files mkdocs-glightbox mkdocstrings[python]

      - run: mkdocs gh-deploy --force
