name: pr

on:
  pull_request:
    branches:
      - main

jobs:
  pre-commit-hooks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit pytest cookiecutter
          pre-commit install

      - name: Run pre-commit hooks
        run: pre-commit run --all-files
